### PR TITLE
Variable names were wrong. Bytecode unchanged.

### PR DESCRIPTION
**Pull request by Fenyx4**
This removes the apparent bug on line 788.

### CODE REVIEW

**Comment by cambragol** [comment]
Hmph. Never noticed this before. Better check my version!

**Comment by cambragol** [comment]
I wonder if this was a bug in the original game that made it into the decompiled code too?

**Comment by Fenyx4** [comment]
It isn't actually a bug in the game. The correct values from the attribute array in 666 and 667 end up in the correct attribues in game.
The compiled bytecode doesn't change with my changes here.
The variables simply got named wrong.

**Comment by cambragol** [comment]
Right. Got it.

**Comment by ergonomy-joe** [comment]
I merged @Fenyx4 's fix in my code. Didn't use the pull request feature though. I hope no one minds.

**Pull request closed without merging**
